name: nanoquery
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.2
  - pyarrow>=15
  - numpy>=1.26
  - ipykernel
  - psutil
  - pytest
  - pip
  - pip:
      # keep empty or add extras you prefer
      # - memory-profiler
      # - black
      # - ruff
